version: '3'
services:
  http:
    image: nginx
    volumes:
      - "./infrastructure/mysite.conf:/etc/nginx/conf.d/000_site.conf"
      - "./app:/var/www/html"
    ports:
      - "8080:80"
    command: /bin/bash -c "cat /etc/nginx/conf.d/000_site.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - php-fpm
    networks:
      - nginx:php-net

  php-fpm:
    build:
      context: ./infrastructure/docker
    volumes:
      - "./app:/var/www/html"
    networks:
      - nginx:php-net

  composer:
    image: "composer"
    volumes:
      - "./app:/app"
    command: install

networks:
  nginx:php-net:
    driver: bridge