version: '3'
services:
  http:
    image: nginx
    volumes:
      - "./infrastructure/mysite.conf:/etc/nginx/conf.d/000_site.conf"
      - "./app:/code"
    ports:
      - "80:80"
    command: /bin/bash -c "cat /etc/nginx/conf.d/000_site.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./infrastructure/docker
    volumes:
      - "./app:/code"

  composer:
    image: "composer"
    volumes:
      - "./app:/app"
    command: install

